<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Adam">
<meta name="dcterms.date" content="2024-11-30">

<title>Linear Regression</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="linear_reg_final_files/libs/clipboard/clipboard.min.js"></script>
<script src="linear_reg_final_files/libs/quarto-html/quarto.js"></script>
<script src="linear_reg_final_files/libs/quarto-html/popper.min.js"></script>
<script src="linear_reg_final_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="linear_reg_final_files/libs/quarto-html/anchor.min.js"></script>
<link href="linear_reg_final_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="linear_reg_final_files/libs/quarto-html/quarto-syntax-highlighting-2486e1f0a3ee9ee1fc393803a1361cdb.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="linear_reg_final_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="linear_reg_final_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="linear_reg_final_files/libs/bootstrap/bootstrap-5bdc1ec511977dd36301403cf8f4f68d.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Linear Regression</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Adam </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 30, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="analysis" class="level1">
<h1>4. Analysis</h1>
<section id="section-3.-simple-and-multiple-linear-regressions" class="level2">
<h2 class="anchored" data-anchor-id="section-3.-simple-and-multiple-linear-regressions">Section 3. Simple and Multiple Linear Regressions</h2>
<p>This part of the analysis focuses on applying linear regression to address the three research questions outlined in the introduction. We will explore whether there is a relationship between students’ academic workload and the prevalence of mental health issues; between academic workload, the amount of sleep students get, and its impact on mental health; and finally, between mental health, students’ living situations, and their ability to maintain a work-life balance. All of these relationships were found to be statistically significant!</p>
</section>
<section id="research-question-1" class="level2">
<h2 class="anchored" data-anchor-id="research-question-1">Research Question 1</h2>
<section id="a.-relevant-graphs-tables" class="level3">
<h3 class="anchored" data-anchor-id="a.-relevant-graphs-tables">a. Relevant Graphs &amp; Tables</h3>
<p>Research Question 1 is concerned with determining whether there is a relationship between students’ academic workload and the prevalence of mental health issues in students. To answer this question, we start by plotting a boxplot of academic workload by stress level. This plot suggests that higher stress levels are associated with a higher academic workload. On average, students who “Always” or “Sometimes” feel stressed tend to have a higher workload than those who “Never” feel stressed.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Boxplot of Academic Workload by Stress Level](boxplot_academic_workload_by_stress.png){width=80%} -->
</section>
<section id="b.-necessary-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="b.-necessary-assumptions">b. Necessary Assumptions</h3>
<p>To confirm this association, we implement a simple linear regression model, where the dependent variable is stress_numeric (the stress variable, converted to numeric values), and the independent variable is academic_workload. To implement this model, we check the following assumptions using the following plot of the residuals:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Residuals Plot](residuals_rq1.png){width=80%} -->
<ol type="1">
<li>Independence of errors: Since the plot has no noticable pattern, the independence assumption is satisfied.</li>
<li>Normality of errors: Since our sample size is sufficiently large, by the Central Limit Theorem the sample mean (and by extension, the sampling distribution of residuals) approximately follows a Normal distribution.</li>
<li>Homogeneity of variances amongst errors: Since the residuals plot has a “horizontal band appearance”, this suggests that variance of the residuals are the same for all values of the independent variable academic_workload.</li>
</ol>
<p>Since all the assumptions are met, we run the regression using the code in Appendix B.</p>
</section>
<section id="c.-computation-and-statistical-test-output" class="level3">
<h3 class="anchored" data-anchor-id="c.-computation-and-statistical-test-output">c.&nbsp;Computation and Statistical Test Output</h3>
<p>The regression analysis produced the following results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Estimate</th>
<th>SE</th>
<th>t-value</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (<span class="math inline">\(\beta_0\)</span>)</td>
<td>1.22389</td>
<td>0.40942</td>
<td>2.989</td>
<td>0.00495</td>
</tr>
<tr class="even">
<td>Slope (<span class="math inline">\(\beta_1\)</span>)</td>
<td>0.32655</td>
<td>0.09945</td>
<td>3.284</td>
<td>0.00224</td>
</tr>
</tbody>
</table>
<hr>
<p>The residual standard error is 0.5353 with 37 degrees of freedom. The <span class="math inline">\(R^2\)</span> value is 0.2256, and the F-statistic is <span class="math inline">\(F(1, 37) = 10.78\)</span>, with a p-value of <span class="math inline">\(0.002\)</span>.</p>
<p>The equation of the regression line is given by: <span class="math display">\[
\text{Stress} = 1.22389 + 0.32655 \cdot \text{Academic Workload}
\]</span></p>
</section>
<section id="d.-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="d.-interpretation">d.&nbsp;Interpretation</h3>
<p>The small <span class="math inline">\(p-value = 0.00224\)</span> indicates that academic workload is a significant predictor of stress. Therefore, we can conclude that there is a significant relationship between students academic workload and their stress levels.</p>
</section>
</section>
<section id="research-question-2" class="level2">
<h2 class="anchored" data-anchor-id="research-question-2">Research Question 2</h2>
<section id="a.-relevant-graphs-tables-1" class="level3">
<h3 class="anchored" data-anchor-id="a.-relevant-graphs-tables-1">a. Relevant Graphs &amp; Tables</h3>
<p>Research Question 2 investigates whether there is a relationship between students’ academic workload, the amount of sleep they get, and impact on mental health. Since the ANOVA above showed no significant relationship between stress and hours of sleep, we investigate the effect of another factor, the number of missed social events.To begin, we plot a boxplot of hours of sleep by the number of missed social events. This plot suggests students who miss more social events tend to have fewer hours of sleep on average.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Boxplot of Hours Sleep by Missed Social Events](boxplot_hours_sleep_by_missed_social_events.png){width=80%} -->
</section>
<section id="b.-necessary-assumptions-1" class="level3">
<h3 class="anchored" data-anchor-id="b.-necessary-assumptions-1">b. Necessary Assumptions</h3>
<p>To assess this relationship, we use a multiple linear regression model with hours of sleep as the dependent variable, and academic workload and missed social events as the independent variables. Before interpreting this model, we check the following assumptions:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Residuals Plot](residuals_rq2.png){width=80%}
![QQ Plot](qq_rq2.png){width=80%} -->
<ol type="1">
<li>Independence of errors: The residual plot shown above indicates no clear patterns, which suggests independence.</li>
<li>Normality of errors: Since the sample size is large, the Central Limit Theorem implies that the residuals should approximate a normal distribution. Also, a QQ-plot confirms approximate normality.</li>
<li>Homogeneity of variances: The residuals plot exhibits a roughly horizontal band, indicating constant variance across predicted values.</li>
<li>No multi-collinearity: We calculated the VIF of each independent variable, and found that <span class="math inline">\(VIF(\text{academic\_workload}) = 1.076844\)</span>, and <span class="math inline">\(VIF(\text{missed\_social\_events}) = 1.076844\)</span>. Since they are both less than 5,this indicates there is little correlation between them.</li>
</ol>
<p>With all assumptions adequately met, we proceed with the regression analysis. The code used to generate the model can be found in Appendix B.</p>
</section>
<section id="c.-computation-and-statistical-test-output-1" class="level3">
<h3 class="anchored" data-anchor-id="c.-computation-and-statistical-test-output-1">c.&nbsp;Computation and Statistical Test Output</h3>
<p>The regression analysis produced the following results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Estimate</th>
<th>SE</th>
<th>t-value</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (<span class="math inline">\(\beta_0\)</span>)</td>
<td>8.5521</td>
<td>0.6661</td>
<td>12.838</td>
<td><span class="math inline">\(5.3 \times 10^{-15}\)</span></td>
</tr>
<tr class="even">
<td>Slope 1 (<span class="math inline">\(\beta_1\)</span>)</td>
<td>-0.1412</td>
<td>0.1666</td>
<td>-0.848</td>
<td>0.40208</td>
</tr>
<tr class="odd">
<td>Slope 2 (<span class="math inline">\(\beta_2\)</span>)</td>
<td>-0.3763</td>
<td>0.1194</td>
<td>-3.151</td>
<td>0.00327</td>
</tr>
</tbody>
</table>
<hr>
<p>The residual standard error is 0.864 with 36 degrees of freedom. The <span class="math inline">\(R^2\)</span> value is 0.2653, the adjusted <span class="math inline">\(R^2\)</span> is 0.2245, and the F-statistic is <span class="math inline">\(F(2, 36) = 6.5\)</span>, with a p-value of <span class="math inline">\(0.003889\)</span>.</p>
<p>The equation of the regression line is given by: <span class="math display">\[
\text{Hours of Sleep} = 8.5521 − 0.1412 \cdot \text{Academic Workload} - 0.3763 \cdot \text{Missed Social Events}
\]</span></p>
</section>
<section id="d.-interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="d.-interpretation-1">d.&nbsp;Interpretation</h3>
<p>The output of the regression analysis shows that the missed social events has a statistically significant negative association with hours of sleep (p = 0.00327). However, academic workload does not have a significant relationship with hours of sleep (p = 0.40208).</p>
</section>
</section>
<section id="research-question-3" class="level2">
<h2 class="anchored" data-anchor-id="research-question-3">Research Question 3</h2>
<section id="a.-relevant-graphs-tables-2" class="level3">
<h3 class="anchored" data-anchor-id="a.-relevant-graphs-tables-2">a. Relevant Graphs &amp; Tables</h3>
<p>Research Question 3 examines whether mental health, represented by stress levels, is affected by students’ living situations and their ability to maintain a work-life balance. To explore this relationship, we first plot a boxplot of stress level by missed social events, with students grouped by stress categories (“Always,” “Never,” and “Sometimes”). This plot suggests that students who miss social events “Always” or “Sometimes” have higher stress levels, while those who “Never” miss social events report lower stress levels.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Boxplot of Missed Social Events by Stress](boxplot_missed_social_events_by_stress.png){width=80%} -->
</section>
<section id="b.-necessary-assumptions-2" class="level3">
<h3 class="anchored" data-anchor-id="b.-necessary-assumptions-2">b. Necessary Assumptions</h3>
<p>To investigate the impact of missed social events and living situations on stress, we use a multiple linear regression model. The response variable is stress (in numeric form), and the predictors are missed social events and living situation. We verify the following assumptions:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="linear_reg_final_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Residuals Plot](residuals_rq3.png){width=80%}
![QQ Plot](qq_rq3.png){width=80%} -->
<ol type="1">
<li>Independence of errors: The residual plot indicates no clear patterns, suggesting that the errors are independent.</li>
<li>Normality of errors: Since the sample size is large, the Central Limit Theorem implies that the residuals should approximate a normal distribution. Also, a QQ-plot confirms approximate normality.</li>
<li>Homogeneity of variances: The residuals plot exhibits a roughly horizontal band, indicating constant variance across predicted values.</li>
<li>No multi-collinearity: We calculated the VIF of each independent variable, and found that <span class="math inline">\(VIF(\text{missed\_social\_events}) = 1.009045\)</span>, and <span class="math inline">\(VIF(\text{living\_situation}) = 1.003006\)</span>. Since both VIF values are close to 1, there’s no indication of multicollinearity in this model.</li>
</ol>
<p>With all assumptions adequately met, we proceed with the regression analysis. The code used to generate the model can be found in Appendix B.</p>
</section>
<section id="c.-computation-and-statistical-test-output-2" class="level3">
<h3 class="anchored" data-anchor-id="c.-computation-and-statistical-test-output-2">c.&nbsp;Computation and Statistical Test Output</h3>
<p>The regression analysis produced the following results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Estimate</th>
<th>SE</th>
<th>t-value</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (<span class="math inline">\(\beta_0\)</span>)</td>
<td>1.93006</td>
<td>0.27980</td>
<td>6.898</td>
<td><span class="math inline">\(6.02 \times 10^{-8}\)</span></td>
</tr>
<tr class="even">
<td>Slope 1 (<span class="math inline">\(\beta_1\)</span>)</td>
<td>0.15560</td>
<td>0.07721</td>
<td>2.015</td>
<td>0.0518</td>
</tr>
<tr class="odd">
<td>Slope 2 (<span class="math inline">\(\beta_2\)</span>)</td>
<td>0.81061</td>
<td>0.39928</td>
<td>2.030</td>
<td>0.0502</td>
</tr>
<tr class="even">
<td>Slope 3 (<span class="math inline">\(\beta_3\)</span>)</td>
<td>0.21206</td>
<td>0.28310</td>
<td>0.749</td>
<td>0.4590</td>
</tr>
<tr class="odd">
<td>Slope 4 (<span class="math inline">\(\beta_4\)</span>)</td>
<td>0.30493</td>
<td>0.25406</td>
<td>1.200</td>
<td>0.2383</td>
</tr>
</tbody>
</table>
<hr>
<p>The residual standard error is 0.5745 with 34 degrees of freedom. The <span class="math inline">\(R^2\)</span> value is 0.1806, the adjusted <span class="math inline">\(R^2\)</span> value is 0.08416, and the F-statistic is <span class="math inline">\(F(4, 34) = 1.873\)</span>, with a p-value of <span class="math inline">\(0.1378\)</span>.</p>
<p>The equation of the regression line is given by: <span class="math display">\[
\begin{array}{lllllll}
\text{Stress} &amp;=&amp; 1.93006 &amp;+&amp; 0.15560 \cdot \text{Missed Social Events} &amp;+&amp; 0.81061 \cdot \text{Living On Campus} \\
              &amp; &amp;         &amp;+&amp; 0.21206 \cdot \text{Living With Family}   &amp;+&amp; 0.30493 \cdot \text{Living With Roommates}
\end{array}
\]</span></p>
</section>
<section id="d.-interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="d.-interpretation-2">d.&nbsp;Interpretation</h3>
<p>The results indicate that missed social events are a marginally significant predictor of stress levels (p = 0.0518). Living situation, specifically living on campus, is also a marginally significant predictor (p = 0.0502). However, living with family (p = 0.4590) and living with roommates (p = 0.2383) do not significantly predict stress.</p>
</section>
</section>
</section>
<section id="limitations" class="level1">
<h1>6. Limitations</h1>
<p>Three major limitations that our study faced were failing to reject the null hypotheses, survey limitations, and the indirect nature of our research.</p>
<ol type="1">
<li><p>Failing to Reject Null Hypotheses<br>
Many additional tests not included in this report failed to produce statistically significant results. For example, one linear regression test concluded that there is no relationship between academic workload and some mental health issues. This sort of result seemed counterintuitive and difficult to accept, which suggested there might be other factors that influence mental health that we did not consider.</p></li>
<li><p>Survey Limitations<br>
Students may have rushed through the survey in order to recieve course credit, without taking the time to reflect on their responses. Also, students may have not felt comfortable answering questions about their mental health truthfully, which could have led to response bias.</p></li>
<li><p>Indirect Nature of Research<br>
Mental health is a complex topic, and it is difficult to be certain about the reliability and validity of our results when our study relied on indirect measures such as stress and anxiety to represent the broad spectrum of mental health.</p></li>
</ol>
<p>In the future, to address these limitations, we plan to incorporate attention-check questions to identify rushed or careless responses. We will also explore additional variables that may influence mental health to ensure a comprehensive understanding of the complexities of mental health. Finally, some open-ended questions could help students elaborate on their responses.</p>
<ol type="1">
<li><p>Many additional tests not included in this report failed to produce statistically significant results. For example, one linear regression test concluded that there is no relationship between academic workload and some mental health issues. This sort of result seemed counterintuitive and difficult to accept, which suggested there might be other factors that influence mental health that we did not consider.</p></li>
<li><p>Failing to Reject Null Hypotheses &nbsp;&nbsp;Many additional tests not included in this report failed to produce statistically significant results. For example, one linear regression test concluded that there is no relationship between academic workload and some mental health issues. This sort of result seemed counterintuitive and difficult to accept, which suggested there might be other factors that influence mental health that we did not consider.</p></li>
<li><p>Failing to Reject Null Hypotheses <br> Many additional tests not included in this report failed to produce statistically significant results. For example, one linear regression test concluded that there is no relationship between academic workload and some mental health issues. This sort of result seemed counterintuitive and difficult to accept, which suggested there might be other factors that influence mental health that we did not consider.</p></li>
</ol>
</section>
<section id="conclusion" class="level1">
<h1>7. Conclusion</h1>
<p>LINEAR REGRESSION CONCLUSION ONLY The linear regression analysis conducted for the three research questions of this study provides valuable insights into the factors affecting student stress and mental health. For Research Question 1, we found a significant positive relationship between academic workload and stress levels, suggesting that students with heavier workloads tend to experience higher levels of stress. In Research Question 2, while academic workload did not significantly impact the amount of sleep, missed social events were found to significantly reduce hours of sleep, which may contribute to poor mental health. For Research Question 3, missed social events and living situation were marginally significant predictors of stress, indicating that students who miss social events or live on campus tend to report higher stress levels. These findings highlight the importance of considering multiple factors in understanding a student’s overall well-being. However, the limitations of this analysis, including potential issues with sample randomization and measurement quality, should be addressed in future research to enhance the robustness and accuracy of the results. Future studies should also explore other possible variables, such as social support and coping mechanisms, which may further explain the mental health challenges faced by students.</p>
<p>TODO - Explain how the random sample was chosen - Include explanation for removing outliers - Move R code into same file - Remove ‘in the appendix’ wording - Fix limitations section - Border for residuals maybe - any missing places - fix spacing between graphs and text</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>