<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Chau Nguyen, John Luc, Adam Tadj, Sunwoo Hwang, Sabrina Seiler">
<meta name="dcterms.date" content="2024-12-02">

<title>STA304 Report</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="sta304_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="sta304_report_files/libs/quarto-html/quarto.js"></script>
<script src="sta304_report_files/libs/quarto-html/popper.min.js"></script>
<script src="sta304_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="sta304_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="sta304_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="sta304_report_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="sta304_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="sta304_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="sta304_report_files/libs/bootstrap/bootstrap-8a79a254b8e706d3c925cde0a310d4f0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">STA304 Report</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Chau Nguyen, John Luc, Adam Tadj, Sunwoo Hwang, Sabrina Seiler </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">December 2, 2024</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="i.-abstract" class="level1">
<h1>I. Abstract</h1>
<p>University students frequently face challenges that contribute to mental health issues such as stress and anxiety. This study examines the relationship between mental health and factors such as academic workload, hours of sleep, living situation, and work-life balance. Data were collected through a Google Form survey administered to students in a third-year statistics survey &amp; sampling course, where participants rated their agreement with statements related to various mental health indicators. The results showed a significant relationship between academic workload and stress levels. While no significant relationship was found between stress levels and hours of sleep, we observed a significant association between hours of sleep and missed social events. Additionally, no statistically significant relationship was identified between stress levels and living situation, though a marginally significant relationship was found between living situation and missed social events. Since we were not able to reach most of the conclusions that we expected, we plan to consider other factors that might influence mental health, and also incorporate attention-check questions to identify rushed responses.</p>
</section>
<section id="ii.-introduction" class="level1">
<h1>II. Introduction</h1>
<p>The academic workload faced by university students has increasingly become one of the critical variables for university students concerning mental health. Given a broader context of increasing academic challenges, many students experience heightened stress levels, which impact various aspects of their well-being, including sleep quality, work-life balance, and several mental health issues.</p>
<p>First, commonly reported mental health issues, including anxiety, depression and stress, have been found to correlate with academic pressures in highly competitive or rigorous programs where students may feel unable to meet academic and personal expectations (Beiter et al., 2015). Second, research indicates that students experiencing high academic workload tend to report poorer sleep quality and shorter sleep duration, which, in turn, can exacerbate mental health problems and academic performance challenges (Hershner &amp; Chervin, 2014; Galambos et al., 2009). Third, students’ living environments and their ability to maintain a balanced lifestyle can also significantly impact mental health, since living in a more supportive and conducive environment positions students to better manage academic responsibilities and personal well-being (Kim &amp; Koh, 2018).</p>
<p>Given the above potential factors, we seek to address the following research questions in this report:</p>
<ul>
<li><p><strong>Research Question 1:</strong> Is there an association between students’ academic workload and the amount of mental health issues?</p>
<ul>
<li><p><strong>Null Hypothesis:</strong> There is no association between academic workload and the amount of mental health issues.</p></li>
<li><p><strong>Alternative Hypothesis:</strong> There is a significant association between academic workload and the amount of mental health issues.</p></li>
</ul></li>
<li><p><strong>Research Question 2:</strong> How does the academic workload affect the quality/length of sleep and its subsequent impact on students’ mental health?</p>
<ul>
<li><p><strong>Null Hypothesis:</strong> Academic workload does not affect the quality or length of sleep, nor does it affect students’ mental health.</p></li>
<li><p><strong>Alternative Hypothesis:</strong> Academic workload significantly affects the quality and/or amount of sleep students get, which affects mental health.</p></li>
</ul></li>
<li><p><strong>Research Question 3:</strong> Is mental health affected by students’ living situations or students’ ability to maintain work-life balance?</p>
<ul>
<li><p><strong>Null Hypothesis:</strong> Students’ mental health is not affected by their living situation or their ability to maintain a work-life balance.</p></li>
<li><p><strong>Alternative Hypothesis:</strong> Students’ mental health is significantly affected by their living situation and their ability to maintain a work-life balance.</p></li>
</ul></li>
</ul>
<p>This study focuses on students enrolled in STA304H5 during Fall 2024, aiming to provide valuable insights into the effects of academic workload on their overall well-being. By exploring these relationships, the findings may inform strategies to enhance student support services and improve academic experiences.</p>
</section>
<section id="iii.-methodology" class="level1">
<h1>III. Methodology</h1>
<!--
Initial setup
-->
<section id="data-collection" class="level2">
<h2 class="anchored" data-anchor-id="data-collection">1. Data Collection</h2>
<p>Between October 8th, 2024, and October 20th, 2024, the questionnaire’s Google Form link was posted on the STA304H5 Piazza course discussion board. We utilized Simple Random Sampling (SRS) by using the R random generator to randomly sample 45 students from the received questionnaire responses. This method was chosen because it gives all respondents an equal chance of being included in the sample, making the sample representative. This experiment does not require methods like stratified or cluster sampling because the population in this experiment is relatively uniform and doesn’t need to be divided into strata or clusters.</p>
<p>We considered alternative methods, such as stratified sampling or cluster sampling. However, these methods are more suitable when the characteristics of specific subpopulations need to be accounted for. Since the characteristics of students taking STA304 were expected to be similar, we decided that it would not be meaningful to distinguish between the subpopulations. Since our goal was to capture the characteristics of all students, we determined that SRS was the most appropriate method for this experiment.</p>
<p>On the questionnaire, we asked participants to complete 10 short-answer questions inquiring about academic workload, average hours studied weekly, amounts of experienced stress-related symptoms (stress, anxiety, concentration difficulty), hours of sleep per night, current living situation, and experienced common issues caused by academic workload (time management, social life, financial).</p>
</section>
<section id="target-population" class="level2">
<h2 class="anchored" data-anchor-id="target-population">2. Target Population</h2>
<p>The target population consists of students enrolled in the STA304H5 course during the Fall 2024 semester.</p>
</section>
<section id="sampling-method" class="level2">
<h2 class="anchored" data-anchor-id="sampling-method">3. Sampling Method</h2>
<p>We will use <strong>Simple Random Sampling (SRS)</strong> by combining both sections of the STA304H5 course and selecting a random sample of students from the pool.</p>
</section>
<section id="variables-of-interest" class="level2">
<h2 class="anchored" data-anchor-id="variables-of-interest">4. Variables of interest</h2>
<p>The following variables were identified for the research:</p>
<section id="i.-academic-workload" class="level3">
<h3 class="anchored" data-anchor-id="i.-academic-workload">i. Academic Workload</h3>
<p>Academic workload is defined as the number of assignments, projects, and exams and the overall demands of a course. The purpose of this study is to see if a high academic workload is associated with increased mental health problems, such as stress. Academic workload was measured through a questionnaire on a scale of 1 (very light), 2 (light), 3 (moderate), 4 (heavy) and 5 (very heavy).</p>
</section>
<section id="ii.-living-situation" class="level3">
<h3 class="anchored" data-anchor-id="ii.-living-situation">ii. Living Situation</h3>
<p>We divided students’ living arrangements into four categories: Living alone, living with family, living with roommates, and living in on-campus housing. These living arrangements are important variables that have a significant impact on students’ mental health and academic stress.</p>
</section>
<section id="iii.-study-hours" class="level3">
<h3 class="anchored" data-anchor-id="iii.-study-hours">iii. Study Hours</h3>
<p>Study time is an important indicator of students’ time management and academic performance. This study analyzes the relationship between study time and mental health , exploring whether over studying leads to stress reduction or instead causes mental stress and anxiety. Study hours were measured by entering the number of hours of study per week.</p>
</section>
<section id="iv.-mental-health-symptoms-stress-anxiety-and-concentration-difficulties" class="level3">
<h3 class="anchored" data-anchor-id="iv.-mental-health-symptoms-stress-anxiety-and-concentration-difficulties">iv. Mental Health Symptoms (Stress, Anxiety, and Concentration Difficulties)</h3>
<p>These symptoms are key indicators of students’ mental health and may be influenced by academic workload and living conditions. Understanding these relationships helps target interventions and support strategies to improve students’ mental well-being. These symptoms were measured through a questionnaire on a scale of 1 (never) 2 (sometimes) and 3 (always).</p>
</section>
</section>
<section id="sample-size" class="level2">
<h2 class="anchored" data-anchor-id="sample-size">5. Sample Size</h2>
<p>In our research, we applied Simple Random Sampling (SRS) on 200 students. Now, to find out the sample size using the bound of error as 0.29, we used the following formula for the width of confidence interval: <span class="math display">\[
D = \frac{B^2}{4}
\]</span></p>
<p>Where <span class="math inline">\(B = 0.29\)</span>, giving: <span class="math display">\[
D = \frac{(0.29)^2}{4} = 0.021025
\]</span></p>
<p>Using the standard deviation (<span class="math inline">\(\sigma\)</span>) of the academic workload variable, we computed the required sample size using the formula: <span class="math display">\[
n = \frac{N \times \sigma^2}{(N-1) \times D + \sigma^2}
\]</span> Where:</p>
<p>N = 200 (total population size) B = 0.29 (bound of error) D = B²/4 = 0.021025 <span class="math inline">\(\sigma\)</span> is approximated as (range of academic workload)/4 range = maximum academic workload - minimum academic workload</p>
<p>To randomize our sampling process, we used R’s random sampling function sample() with a fixed seed (set.seed(1)) to randomly select participants from the full dataset based on the calculated sample size n.</p>
</section>
</section>
<section id="iv.-analysis" class="level1">
<h1>IV. Analysis</h1>
<section id="anova" class="level2">
<h2 class="anchored" data-anchor-id="anova">1. ANOVA</h2>
<p>RQ1 questions if academic workload contributes to a student’s stress levels. To answer this question, ANOVA (analysis of variance) is used to test the difference in average stress levels between students with different academic workloads. All our assumptions are satisfied as samples between the groups were randomly sampled and responses are independent from each other, data from each group is normally distributed (large sample size, n &gt; 30) and variances are approximately the same (obtained <em>p-value</em> of 0.07758 from Barlett’s test, which is above the α = 0.05 significance level.) All categories were converted to categorical data to make them suitable for ANOVA testing.</p>
</section>
</section>
<section id="anova-between-stress-and-academic-workload" class="level1">
<h1>ANOVA between stress and academic workload</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Degrees of Freedom (DF)</th>
<th>Sum of Squares (SS)</th>
<th>Mean Square (MS)</th>
<th>F-value</th>
<th>Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>academic workload</td>
<td>3</td>
<td>3.136</td>
<td>1.0455</td>
<td>4.273</td>
<td>0.0136</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td>27</td>
<td>6.605</td>
<td>0.2446</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>For the relationship between stress and academic workload, we divided the criteria of stress into categories of Never, Sometimes, and Always, and compared each group with an ANOVA test. Since the calculated F-value of 5.121 is larger than the critical F-value of 2.874 at a 5% significance level with (3, 35) degrees of freedom, we reject the null hypothesis. Therefore, there is a statistically significant relationship between student academic workload and levels of stress.</p>
</section>
<section id="anova-between-stress-and-hours_sleep" class="level1">
<h1>ANOVA between stress and hours_sleep</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 22%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 8%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Degrees of Freedom (DF)</th>
<th>Sum of Squares (SS)</th>
<th>Mean Square (MS)</th>
<th>F-value</th>
<th>Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>sleep</td>
<td>2</td>
<td>1.242</td>
<td>0.6210</td>
<td>2.046</td>
<td>0.148</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td>28</td>
<td>8.500</td>
<td>0.3036</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>In the case of the relationship between Stress and Sleep, we ran an ANOVA test to convert sleep into categorical data, dividing it into 6 hours or less, between 6 and 8 hours, and more than 8 hours. Since the calculated F-value of 0.163 is smaller than the critical F-value of 3.259 at the 5% significance level with (2, 36) degrees of freedom, we fail to reject the null hypothesis. Therefore, there is no statistically significant relationship between hours of sleep and levels of stress among students. This suggests that variations in hours of sleep do not significantly affect variations in stress levels.</p>
</section>
<section id="anova-between-stress-and-missed-social-events" class="level1">
<h1>ANOVA between stress and missed social events</h1>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 19%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Variable</th>
<th>Degrees of Freedom (DF)</th>
<th>Sum of Squares (SS)</th>
<th>Mean Square (MS)</th>
<th>F-value</th>
<th>Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>missed_social_events</td>
<td>4</td>
<td>1.220</td>
<td>0.3049</td>
<td>0.93</td>
<td>0.462</td>
</tr>
<tr class="even">
<td>Residuals</td>
<td>26</td>
<td>8.522</td>
<td>0.3278</td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>This relationship between stress and missed social events, we ran an ANOVA test to convert hours of study into categorical data, dividing into 0-10 hours as “Low”, 10-20 hours as “Medium” and 20 or more as “High”. Since the calculated F-value was 1.092 and this is less than the critical value, 2.629 (<em>df</em>=4, <em>df</em>=34). Therefore, we fail to reject the null hypothesis. This means that <strong>stress levels</strong> and <strong>missed social events</strong> do not have a significant relationship.</p>
<p>Since the calculated F-value of 1.092 is smaller than the critical F-value of 2.649 at the 5% significance level with (4, 34) degrees of freedom, we fail to reject the null hypothesis. This conclusion is also supported by the <em>p-value</em> of 0.376, which is greater than the significance level of 0.05. Therefore, there is no statistically significant relationship between stress levels and missed social events among students.</p>
</section>
<section id="chi-square-test-of-independence" class="level1">
<h1>2. Chi-square Test of Independence</h1>
<p>Research Question 1 questions if there is a relationship between the academic workload of a student and their mental health. Research question 3 questions if there is a relationship between students’ living situation or ability to maintain work-life balance. Our assumption that the data is randomly sampled holds given our method of sampling outlined above. To prove that there exists a relationship between these variables, we want to use the chi square test of independence. We use <span class="math inline">\(\alpha = 0.05\)</span> as the significance level.</p>
<section id="chi-square-test-between-academic-workload-and-stress" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-academic-workload-and-stress">Chi Square Test between Academic Workload and Stress</h2>
<p><span class="math inline">\(\chi^2 = 25.936\)</span>, <em>df</em> = 6, <em>p-value</em> = 0.0002288</p>
<p>Since the calculated <em>p-value</em> was 0.0002288 and is less than <span class="math inline">\(\alpha = 0.05\)</span>, we reject the null hypothesis. This indicates that there is a significant association between academic workload and the stress levels of a student.</p>
</section>
<section id="chi-square-test-between-academic-workload-and-anxiety" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-academic-workload-and-anxiety">Chi Square Test between Academic Workload and Anxiety</h2>
<p><span class="math inline">\(\chi^2 =14.113\)</span>,<em>df</em>=6, <em>p-value</em> =0.0284</p>
<p>Since the calculated <em>p-value</em> was 0.0284 and is less than <span class="math inline">\(\alpha = 0.05\)</span>, we reject the null hypothesis. There is enough statistical evidence that there is a significant association between the academic workload and the anxiety levels of a student.</p>
</section>
<section id="chi-square-test-between-academic-workload-and-concentration" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-academic-workload-and-concentration">Chi Square Test between Academic Workload and Concentration</h2>
<p><span class="math inline">\(\chi^2 =6.5\)</span>, <em>df</em>=6, <em>p-value</em> =0.3696</p>
<p>Since the calculated <em>p-value</em> was 0.3696 and is greater than <span class="math inline">\(\alpha = 0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence to indicate that the academic workload and the The concentration levels of a student are related.</p>
</section>
<section id="chi-square-test-between-living-situation-and-stress" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-living-situation-and-stress">Chi Square Test between Living Situation and Stress</h2>
<p><span class="math inline">\(\chi^2 =4.9936\)</span>, <em>df</em>=6, <em>p-value</em> =0.5446</p>
<p>Since the calculated <em>p-value</em> was 0.5446 and is greater than <span class="math inline">\(\alpha = 0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the living situation and the stress levels of a student are related.</p>
</section>
<section id="chi-square-test-between-living-situation-and-anxiety" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-living-situation-and-anxiety">Chi Square Test between Living Situation and Anxiety</h2>
<p><span class="math inline">\(\chi^2=6.6042\)</span>, <em>df</em>=6, <em>p-value</em> =0.359</p>
<p>Since the calculated <em>p-value</em> was 0.359 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the living situation and the anxiety levels of a student are related.</p>
</section>
<section id="chi-square-test-between-living-situation-and-concentration" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-living-situation-and-concentration">Chi Square Test between Living Situation and Concentration</h2>
<p><span class="math inline">\(\chi^2\)</span> =2.8773, <em>df</em>=6, <em>p-value</em> =0.8241</p>
<p>Since the calculated <em>p-value</em> was 0.8241 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the living situation and the concentration levels of a student are related.</p>
</section>
<section id="chi-square-test-between-time-management-and-stress" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-time-management-and-stress">Chi Square Test between Time Management and Stress</h2>
<p><span class="math inline">\(\chi^2\)</span> =10.894, <em>df</em>=8, <em>p-value</em> =0.2078</p>
<p>Since the calculated <em>p-value</em> was 0.2078 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the time management skills and the stress levels of a student are related.</p>
</section>
<section id="chi-square-test-between-time-management-and-anxiety" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-time-management-and-anxiety">Chi Square Test between Time Management and Anxiety</h2>
<p><span class="math inline">\(\chi^2\)</span> =6.5567, <em>df</em>=8, <em>p-value</em> =0.5851</p>
<p>Since the calculated <em>p-value</em> was 0.5851 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the time management skills and the anxiety levels of a student are related.</p>
</section>
<section id="chi-square-test-between-time-management-and-concentration" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-time-management-and-concentration">Chi Square Test between Time Management and Concentration</h2>
<p><span class="math inline">\(\chi^2\)</span> =9.3321, <em>df</em>=8, <em>p-value</em> =0.3151</p>
<p>Since the calculated <em>p-value</em> was 0.3151 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the time management skills and the concentration levels of a student are related.</p>
</section>
<section id="chi-square-test-between-financials-and-stress" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-financials-and-stress">Chi Square Test between Financials and Stress</h2>
<p><span class="math inline">\(\chi^2\)</span> =9.3321, <em>df</em>=8, <em>p-value</em> =0.7223</p>
<p>Since the calculated <em>p-value</em> was 0.3151 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the financial situation and the stress levels of a student are related.</p>
</section>
<section id="chi-square-test-between-financials-and-anxiety" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-financials-and-anxiety">Chi Square Test between Financials and Anxiety</h2>
<p><span class="math inline">\(\chi^2\)</span> =5.3134, <em>df</em>=8, <em>p-value</em> =0.7236</p>
<p>Since the calculated <em>p-value</em> was 0.7236 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the financial situation and the anxiety levels of a student are related.</p>
</section>
<section id="chi-square-test-between-financials-and-concentration" class="level2">
<h2 class="anchored" data-anchor-id="chi-square-test-between-financials-and-concentration">Chi Square Test between Financials and Concentration</h2>
<p><span class="math inline">\(\chi^2\)</span> =6.1471, <em>df</em>=8, <em>p-value</em> =0.6308</p>
<p>Since the calculated <em>p-value</em> was 0.6308 and is greater than <span class="math inline">\(\alpha=0.05\)</span>, we fail to reject the null hypothesis. There isn’t enough statistical evidence that the financial situation and the concentration levels of a student are related.</p>
</section>
</section>
<section id="section-3.-simple-and-multiple-linear-regressions" class="level1">
<h1>Section 3. Simple and Multiple Linear Regressions</h1>
<p>This part of the analysis focuses on applying linear regression to address the three research questions outlined in the introduction. We will explore whether there is a relationship between students’ academic workload and the prevalence of mental health issues; between academic workload, the amount of sleep students get, and its impact on mental health; and finally, between mental health, students’ living situations, and their ability to maintain a work-life balance. All of these relationships were found to be statistically significant.</p>
<section id="research-question-1" class="level2">
<h2 class="anchored" data-anchor-id="research-question-1">1. Research Question 1</h2>
<section id="a.-relevant-graphs-tables" class="level3">
<h3 class="anchored" data-anchor-id="a.-relevant-graphs-tables">a. Relevant Graphs &amp; Tables</h3>
<p>Research Question 1 is concerned with determining whether there is a relationship between students’ academic workload and the prevalence of mental health issues in students. To answer this question, we start by plotting a boxplot of academic workload by stress level. This plot suggests that higher stress levels are associated with a higher academic workload. On average, students who “Always” or “Sometimes” feel stressed tend to have a higher workload than those who “Never” feel stressed.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-2-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Boxplot of Academic Workload by Stress Level](boxplot_academic_workload_by_stress.png){width=80%} -->
</section>
<section id="b.-necessary-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="b.-necessary-assumptions">b. Necessary Assumptions</h3>
<p>To confirm this association, we implement a simple linear regression model, where the dependent variable is stress_numeric (the stress variable, converted to numeric values), and the independent variable is academic_workload. To implement this model, we check the following assumptions using the following plot of the residuals:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Residuals Plot](residuals_rq1.png){width=80%} -->
<ol type="1">
<li>Independence of errors: Since the plot has no noticable pattern, the independence assumption is satisfied.</li>
<li>Normality of errors: Since our sample size is sufficiently large, by the Central Limit Theorem the sample mean (and by extension, the sampling distribution of residuals) approximately follows a Normal distribution.</li>
<li>Homogeneity of variances amongst errors: Since the residuals plot has a “horizontal band appearance”, this suggests that variance of the residuals are the same for all values of the independent variable academic_workload.</li>
</ol>
<p>Since all the assumptions are met, we may preform the regression analysis.</p>
</section>
<section id="c.-computation-and-statistical-test-output" class="level3">
<h3 class="anchored" data-anchor-id="c.-computation-and-statistical-test-output">c.&nbsp;Computation and Statistical Test Output</h3>
<p>The regression analysis produced the following results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Estimate</th>
<th>SE</th>
<th>t-value</th>
<th><em>p-value</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (<span class="math inline">\(\beta_0\)</span>)</td>
<td>1.22389</td>
<td>0.40942</td>
<td>2.989</td>
<td>0.00495</td>
</tr>
<tr class="even">
<td>Slope (<span class="math inline">\(\beta_1\)</span>)</td>
<td>0.32655</td>
<td>0.09945</td>
<td>3.284</td>
<td>0.00224</td>
</tr>
</tbody>
</table>
<hr>
<p>The residual standard error is <span class="math inline">\(0.5353\)</span> with <span class="math inline">\(37\)</span> degrees of freedom. The <span class="math inline">\(R^2\)</span> value is <span class="math inline">\(0.2256\)</span>, and the F-statistic is <span class="math inline">\(F(1, 37) = 10.78\)</span>, with a <em>p-value</em> of <span class="math inline">\(0.002\)</span>.</p>
<p>The equation of the regression line is given by: <span class="math display">\[
\text{Stress} = 1.22389 + 0.32655 \cdot \text{Academic Workload}
\]</span></p>
</section>
<section id="d.-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="d.-interpretation">d.&nbsp;Interpretation</h3>
<p>The small <span class="math inline">\(p-value = 0.00224\)</span> indicates that academic workload is a significant predictor of stress. Therefore, we can conclude that there is a significant relationship between students’ academic workload and their stress levels.</p>
</section>
</section>
<section id="research-question-2" class="level2">
<h2 class="anchored" data-anchor-id="research-question-2">2. Research Question 2</h2>
<section id="a.-relevant-graphs-tables-1" class="level3">
<h3 class="anchored" data-anchor-id="a.-relevant-graphs-tables-1">a. Relevant Graphs &amp; Tables</h3>
<p>Research Question 2 investigates whether there is a relationship between students’ academic workload, the amount of sleep they get, and impact on mental health. Since the ANOVA above showed no significant relationship between stress and hours of sleep, we investigate the effect of another factor, the number of missed social events. To begin, we plot a boxplot of hours of sleep by the number of missed social events. This plot suggests students who miss more social events tend to have fewer hours of sleep on average.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Boxplot of Hours Sleep by Missed Social Events](boxplot_hours_sleep_by_missed_social_events.png){width=80%} -->
</section>
<section id="b.-necessary-assumptions-1" class="level3">
<h3 class="anchored" data-anchor-id="b.-necessary-assumptions-1">b. Necessary Assumptions</h3>
<p>To assess this relationship, we use a multiple linear regression model with hours of sleep as the dependent variable, and academic workload and missed social events as the independent variables. Before interpreting this model, we check the following assumptions:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Residuals Plot](residuals_rq2.png){width=80%}
![QQ Plot](qq_rq2.png){width=80%} -->
<ol type="1">
<li>Independence of errors: The residual plot shown above indicates no clear patterns, which suggests independence.</li>
<li>Normality of errors: Since the sample size is large, the Central Limit Theorem implies that the residuals should approximate a normal distribution. Also, a QQ-plot confirms approximate normality.</li>
<li>Homogeneity of variances: The residuals plot exhibits a roughly horizontal band, indicating constant variance across predicted values.</li>
<li>No multi-collinearity: We calculated the VIF of each independent variable, and found that <span class="math inline">\(VIF(\text{academic\_workload}) = 1.076844\)</span>, and <span class="math inline">\(VIF(\text{missed\_social\_events}) = 1.076844\)</span>. Since they are both less than <span class="math inline">\(5\)</span>, this indicates there is little correlation between them.</li>
</ol>
<p>With all assumptions adequately met, we proceed with the regression analysis.</p>
</section>
<section id="c.-computation-and-statistical-test-output-1" class="level3">
<h3 class="anchored" data-anchor-id="c.-computation-and-statistical-test-output-1">c.&nbsp;Computation and Statistical Test Output</h3>
<p>The regression analysis produced the following results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Estimate</th>
<th>SE</th>
<th>t-value</th>
<th><em>p-value</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (<span class="math inline">\(\beta_0\)</span>)</td>
<td>8.5521</td>
<td>0.6661</td>
<td>12.838</td>
<td><span class="math inline">\(5.3 \times 10^{-15}\)</span></td>
</tr>
<tr class="even">
<td>Slope 1 (<span class="math inline">\(\beta_1\)</span>)</td>
<td>-0.1412</td>
<td>0.1666</td>
<td>-0.848</td>
<td>0.40208</td>
</tr>
<tr class="odd">
<td>Slope 2 (<span class="math inline">\(\beta_2\)</span>)</td>
<td>-0.3763</td>
<td>0.1194</td>
<td>-3.151</td>
<td>0.00327</td>
</tr>
</tbody>
</table>
<hr>
<p>The residual standard error is <span class="math inline">\(0.864\)</span> with <span class="math inline">\(36\)</span> degrees of freedom. The <span class="math inline">\(R^2\)</span> value is <span class="math inline">\(0.2653\)</span>, the adjusted <span class="math inline">\(R^2\)</span> is <span class="math inline">\(0.2245\)</span>, and the F-statistic is <span class="math inline">\(F(2, 36) = 6.5\)</span>, with a <em>p-value</em> of <span class="math inline">\(0.003889\)</span>.</p>
<p>The equation of the regression line is given by: <span class="math display">\[
\text{Hours of Sleep} = 8.5521 − 0.1412 \cdot \text{Academic Workload} - 0.3763 \cdot \text{Missed Social Events}
\]</span></p>
</section>
<section id="d.-interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="d.-interpretation-1">d.&nbsp;Interpretation</h3>
<p>The output of the regression analysis shows that the missed social events has a statistically significant negative association with hours of sleep (<span class="math inline">\(p = 0.00327\)</span>). However, academic workload does not have a significant relationship with hours of sleep (<span class="math inline">\(p = 0.40208\)</span>).</p>
</section>
</section>
<section id="research-question-3" class="level2">
<h2 class="anchored" data-anchor-id="research-question-3">3. Research Question 3</h2>
<section id="a.-relevant-graphs-tables-2" class="level3">
<h3 class="anchored" data-anchor-id="a.-relevant-graphs-tables-2">a. Relevant Graphs &amp; Tables</h3>
<p>Research Question 3 examines whether mental health, represented by stress levels, is affected by students’ living situations and their ability to maintain a work-life balance. To explore this relationship, we first plot a boxplot of stress level by missed social events, with students grouped by stress categories (“Always,” “Never,” and “Sometimes”). This plot suggests that students who miss social events “Always” or “Sometimes” have higher stress levels, while those who “Never” miss social events report lower stress levels.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Boxplot of Missed Social Events by Stress](boxplot_missed_social_events_by_stress.png){width=80%} -->
</section>
<section id="b.-necessary-assumptions-2" class="level3">
<h3 class="anchored" data-anchor-id="b.-necessary-assumptions-2">b. Necessary Assumptions</h3>
<p>To investigate the impact of missed social events and living situations on stress, we use a multiple linear regression model. The response variable is stress (in numeric form), and the predictors are missed social events and living situation. We verify the following assumptions:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="sta304_report_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<!-- ![Residuals Plot](residuals_rq3.png){width=80%}
![QQ Plot](qq_rq3.png){width=80%} -->
<ol type="1">
<li>Independence of errors: The residual plot indicates no clear patterns, suggesting that the errors are independent.</li>
<li>Normality of errors: Since the sample size is large, the Central Limit Theorem implies that the residuals should approximate a normal distribution. Also, a QQ-plot confirms approximate normality.</li>
<li>Homogeneity of variances: The residuals plot exhibits a roughly horizontal band, indicating constant variance across predicted values.</li>
<li>No multi-collinearity: We calculated the VIF of each independent variable, and found that <span class="math inline">\(VIF(\text{missed\_social\_events}) = 1.009045\)</span>, and <span class="math inline">\(VIF(\text{living\_situation}) = 1.003006\)</span>. Since both VIF values are close to <span class="math inline">\(1\)</span>, there’s no indication of multicollinearity in this model.</li>
</ol>
<p>With all assumptions adequately met, we proceed with the regression analysis.</p>
</section>
<section id="c.-computation-and-statistical-test-output-2" class="level3">
<h3 class="anchored" data-anchor-id="c.-computation-and-statistical-test-output-2">c.&nbsp;Computation and Statistical Test Output</h3>
<p>The regression analysis produced the following results:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 41%">
<col style="width: 17%">
<col style="width: 14%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th>Statistic</th>
<th>Estimate</th>
<th>SE</th>
<th>t-value</th>
<th><em>p-value</em></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept (<span class="math inline">\(\beta_0\)</span>)</td>
<td>1.93006</td>
<td>0.27980</td>
<td>6.898</td>
<td><span class="math inline">\(6.02 \times 10^{-8}\)</span></td>
</tr>
<tr class="even">
<td>Slope 1 (<span class="math inline">\(\beta_1\)</span>)</td>
<td>0.15560</td>
<td>0.07721</td>
<td>2.015</td>
<td>0.0518</td>
</tr>
<tr class="odd">
<td>Slope 2 (<span class="math inline">\(\beta_2\)</span>)</td>
<td>0.81061</td>
<td>0.39928</td>
<td>2.030</td>
<td>0.0502</td>
</tr>
<tr class="even">
<td>Slope 3 (<span class="math inline">\(\beta_3\)</span>)</td>
<td>0.21206</td>
<td>0.28310</td>
<td>0.749</td>
<td>0.4590</td>
</tr>
<tr class="odd">
<td>Slope 4 (<span class="math inline">\(\beta_4\)</span>)</td>
<td>0.30493</td>
<td>0.25406</td>
<td>1.200</td>
<td>0.2383</td>
</tr>
</tbody>
</table>
<hr>
<p>The residual standard error is <span class="math inline">\(0.5745\)</span> with <span class="math inline">\(34\)</span> degrees of freedom. The <span class="math inline">\(R^2\)</span> value is <span class="math inline">\(0.1806\)</span>, the adjusted <span class="math inline">\(R^2\)</span> value is <span class="math inline">\(0.08416\)</span>, and the F-statistic is <span class="math inline">\(F(4, 34) = 1.873\)</span>, with a <em>p-value</em> of <span class="math inline">\(0.1378\)</span>.</p>
<p>The equation of the regression line is given by: <span class="math display">\[
\begin{array}{lllllll}
\text{Stress} &amp;=&amp; 1.93006 &amp;+&amp; 0.15560 \cdot \text{Missed Social Events} &amp;+&amp; 0.81061 \cdot \text{Living On Campus} \\
              &amp; &amp;         &amp;+&amp; 0.21206 \cdot \text{Living With Family}   &amp;+&amp; 0.30493 \cdot \text{Living With Roommates}
\end{array}
\]</span></p>
</section>
<section id="d.-interpretation-2" class="level3">
<h3 class="anchored" data-anchor-id="d.-interpretation-2">d.&nbsp;Interpretation</h3>
<p>The results indicate that missed social events are a marginally significant predictor of stress levels (<span class="math inline">\(p = 0.0518\)</span>). Living situation, specifically living on campus, is also a marginally significant predictor (<span class="math inline">\(p = 0.0502\)</span>). However, living with family (<span class="math inline">\(p = 0.4590\)</span>) and living with roommates (<span class="math inline">\(p = 0.2383\)</span>) do not significantly predict stress.</p>
</section>
</section>
</section>
<section id="discussion-and-results" class="level1">
<h1>Discussion and Results</h1>
<p>For Research Question 1, we wished to investigate whether there is a relationship between a student’s academic workload and the prevalence of mental health issues in students. Preliminarily, we plotted a boxplot to look for any potential relationship between the two variables, and we found that on average, students with higher stress levels tend to have a higher academic workload. We later confirmed this with the simple linear regression test and found that academic workload is a significant predictor of stress.</p>
<p>For Research Question 2, we aimed to investigate whether there is a relationship between students’ academic workload and the amount of sleep they get each night. An earlier test indicated no significant relationship between hours of sleep and academic workload. Therefore, we decided to examine the effect of another factor: the number of social events a student misses on their hours of sleep. Initially, we plotted a boxplot of hours of sleep against the number of missed social events. The graph suggested that, on average, the more social events a student misses, the fewer hours of sleep they tend to get. Our analysis confirmed the earlier finding that academic workload does not have a significant relationship with hours of sleep but also revealed a strong relationship between the number of missed social events and students’ daily hours of sleep.</p>
<p>For Research Question 3, we studied whether mental health is affected by students’ living situations and their ability to maintain a work-life balance. To explore this relationship, we first plotted a boxplot of stress against the number of missed social events. The plot suggested that students who sometimes or always miss social events tend to experience more stress, while those who never miss social events experience less stress. Then, we ran a test that concluded missing social events and living on campus may slightly affect stress levels, although the evidence is not very strong. In contrast, living with family or roommates does not appear to have a significant impact on stress.</p>
<p>ANOVA test between stress and academic workload has the calculated F-value of 4.273, which is larger than the critical F-value of 2.960 at the 5% significance level with (3, 27) degrees of freedom. Therefore, we reject the null hypothesis. There is a statistically significant relationship between student academic workload and levels of stress. This suggests that variations in academic workload are significantly related to variations in stress.</p>
<p>ANOVA test between stress and hours of sleep has the calculated F-value of 0.163, which is smaller than the critical F-value of 3.340 at the 5% significance level with (2, 28) degrees of freedom. Therefore, we fail to reject the null hypothesis. There is no statistically significant correlation between hours of sleep and levels of stress among students. This suggests that variations in hours of sleep do not significantly relate to variations in stress levels.</p>
<p>ANOVA test between stress and missed social events has the calculated F-value of 1.092, which is smaller than the critical F-value of 2.649 at the 5% significance level with (4, 34) degrees of freedom. Therefore, we fail to reject the null hypothesis. This means that stress levels and missed social events do not have a significant relationship.</p>
<p>For the chi square tests of independence between academic workload and stress, anxiety, the respective <em>p-value</em> are 0.0002288 and 0.0284 which are both less than <span class="math inline">\(\alpha=0.05\)</span>, so we reject the null hypothesis. For the chi square tests of independence between academic workload and concentration, the p value is 0.3696, which is greater than <span class="math inline">\(\alpha=0.05\)</span>, therefore we fail to reject the null hypothesis. This suggests that a student’s academic workload has and on their stress or anxiety but not their concentration .</p>
<p>Chi square tests between students’ living situation and their stress, anxiety and concentration yield <em>p-value</em> of 0.5446, 0.359, and 0.8241 respectively. All of these <em>p-value</em> are greater than <span class="math inline">\(\alpha=0.05\)</span>, therefore we fail to reject the null hypothesis for all three of these chi square tests. This suggests that the living situation of a student doesn’t have an association with their stress, anxiety and concentration.</p>
<p>Chi square tests between students’ time management skills and their stress, anxiety and concentration yield <em>p-value</em> of 0.2078, 0.5851, and 0.3151 respectively. All of these <em>p-value</em> are greater than <span class="math inline">\(\alpha=0.05\)</span>, therefore we fail to reject the null hypothesis for all three of these chi square tests. This suggests that a student’s ability to manage their time doesn’t have an association with their stress, anxiety and concentration.</p>
<p>Chi square tests between students’ financials and their stress, anxiety and concentration yield <em>p-value</em> of 0.7223, 0.7236, and 0.6308 respectively. All of these <em>p-value</em> are greater than <span class="math inline">\(\alpha=0.05\)</span>, therefore we fail to reject the null hypothesis for all three of these chi square tests. This suggests that a student’s financial situation doesn’t have an association with their stress, anxiety and concentration.</p>
<p>The results of the multiple and linear regression tests indicate that missed social events are a marginally significant predictor of stress levels (p = 0.0518). Living situation, specifically living on campus, is also a marginally significant predictor (p = 0.0502). However, living with family (p = 0.4590) and living with roommates (p = 0.2383) do not significantly predict stress.</p>
<p>Overall, the results of this study show that stress and anxiety among university students is primarily related to academic factors, with lifestyle factors such as sleep and socializing having less of an impact than expected.</p>
</section>
<section id="limitations" class="level1">
<h1>6. Limitations</h1>
<p>Three major limitations that our study faced were failing to reject the null hypotheses, survey limitations, and the indirect nature of our research.</p>
<ol type="1">
<li><p>Failing to Reject Null Hypotheses<br>
Many additional tests not included in this report failed to produce statistically significant results. For example, one linear regression test concluded that there is no relationship between academic workload and some mental health issues. This sort of result seemed counterintuitive and difficult to accept, which suggested there might be other factors that influence mental health that we did not consider.</p></li>
<li><p>Survey Limitations<br>
Students may have rushed through the survey in order to receive course credit, without taking the time to reflect on their responses. Also, students may have not felt comfortable answering questions about their mental health truthfully, which could have led to response bias.</p></li>
<li><p>Indirect Nature of Research<br>
Mental health is a complex topic, and it is difficult to be certain about the reliability and validity of our results when our study relied on indirect measures such as stress and anxiety to represent the broad spectrum of mental health.</p></li>
</ol>
<p>In the future, to address these limitations, we plan to incorporate attention-check questions to identify rushed or careless responses. We will also explore additional variables that may influence mental health to ensure a comprehensive understanding of the complexities of mental health. Finally, some open-ended questions could help students elaborate on their responses.</p>
</section>
<section id="conclusion" class="level1">
<h1>7. Conclusion</h1>
<p>The linear regression analysis conducted for the three research questions of this study provides valuable insights into the factors affecting student stress and mental health. For Research Question 1, we found a significant positive relationship between academic workload and stress levels, suggesting that students with heavier workloads tend to experience higher levels of stress. In Research Question 2, while academic workload did not significantly impact the amount of sleep, missed social events were found to significantly reduce hours of sleep, which may contribute to poor mental health. For Research Question 3, missed social events and living situations were marginally significant predictors of stress, indicating that students who miss social events or live on campus tend to report higher stress levels. These findings highlight the importance of considering multiple factors in understanding a student’s overall well-being. However, the limitations of this analysis, including potential issues with sample randomization and measurement quality, should be addressed in future research to enhance the robustness and accuracy of the results. Future studies should also explore other possible variables, such as social support and coping mechanisms, which may further explain the mental health challenges faced by students.</p>
<p>Overall, the results of the ANOVA tests show that the stress levels of the students sampled are primarily related to academic factors, with lifestyle factors such as sleep and socializing having less of an impact on their mental health than expected. In addition, this voluntary response method was likely to result in selection bias.</p>
<p>For the chi square tests of independence between academic workload and stress, anxiety, the respective <em>p-value</em> are 0.0002288 and 0.0284 which are both less than <span class="math inline">\(\alpha=0.05\)</span>, so we retain the null hypothesis. For the chi square tests of independence between academic workload and concentration, the p value is 0.3696, which is greater than <span class="math inline">\(\alpha=0.05\)</span>, therefore we reject the null hypothesis. This suggests that a student’s academic workload has an effect on their concentration but not their stress or anxiety.</p>
<p>The linear regression analysis conducted for the three research questions of this study provides valuable insights into the factors affecting student stress and mental health. For Research Question 1, we found a significant positive relationship between academic workload and stress levels, suggesting that students with heavier workloads tend to experience higher levels of stress. In Research Question 2, while academic workload did not significantly impact the amount of sleep, missed social events were found to significantly reduce hours of sleep, which may contribute to poor mental health. For Research Question 3, missed social events and living situations were marginally significant predictors of stress, indicating that students who miss social events or live on campus tend to report higher stress levels. These findings highlight the importance of considering multiple factors in understanding a student’s overall well-being. However, the limitations of this analysis, including potential issues with sample randomization and measurement quality, should be addressed in future research to enhance the robustness and accuracy of the results. Future studies should also explore other possible variables, such as social support and coping mechanisms, which may further explain the mental health challenges faced by students.</p>
</section>
<section id="documentation-of-ai-tool-usage" class="level1">
<h1>8. Documentation of AI tool usage</h1>
<p>The report was completed without the use of generative AI tools such as ChatGPT. All content in this report, including writing, analysis, and interpretation, was created entirely by team members through a collaborative effort and peer review process. We affirm that these are our original thoughts and analyses.</p>
<p>Chi square tests between students’ financials and their stress, anxiety and concentration yield <em>p-value</em> of 0.7223, 0.7236, and 0.6308 respectively. All of these <em>p-value</em> are greater than <span class="math inline">\(\alpha=0.05\)</span>, therefore we reject the null hypothesis for all three of these chi square tests. This means that a student’s financial situation has some effect on their stress, anxiety and concentration.</p>
<p>Overall, the results of the chi square tests of independence indicate that the mental health of a student is primarily related to lifestyle factors, with the academic workload only being related to students’ concentration.</p>
</section>
<section id="limitations-1" class="level1">
<h1>Limitations</h1>
<section id="limitations-2" class="level2">
<h2 class="anchored" data-anchor-id="limitations-2">Limitations</h2>
<p>This experiment investigated the relationship between academic workload, stress, sleep, and work life-balance among STA304 students. There were many difficulties and limitations in conducting this experiment.</p>
<section id="sampling" class="level3">
<h3 class="anchored" data-anchor-id="sampling">Sampling</h3>
<p>First, we used Simple Random Sampling (SRS) to sample the responses from the survey, but I am not sure that randomness was guaranteed. Certain students may have been more active in the survey, which may not generalize the results. Therefore, I think that various methods such as stratified sampling should be used instead of SRS. Also, there is a question of voluntariness, because the students did not voluntarily participate in the survey, but responded as part of their course participation.</p>
</section>
<section id="questionnaire-design" class="level3">
<h3 class="anchored" data-anchor-id="questionnaire-design">Questionnaire Design</h3>
<p>We think that personal bias may occur due to the ambiguity of the questions in the questionnaire, such as the mental health questions, because they are not objective parameters that can be subjective to the people who answer them. These parameters were measured indirectly in the questionnaire, but this can increase the likelihood of measurement error.</p>
</section>
<section id="sample-size-1" class="level3">
<h3 class="anchored" data-anchor-id="sample-size-1">Sample Size</h3>
<p>Third, there is the issue of sample size: while the sample size of this experiment is relatively large compared to the population, the population itself may be limited and the findings may not be generalizable. We would expect the results to be more generalizable if the experiment were conducted on a larger population. A larger population would also allow for us to assume that all of our categorical groups have a normal population distribution, one of the assumptions needed for our ANOVA testing.</p>
</section>
</section>
<section id="conclusion-1" class="level2">
<h2 class="anchored" data-anchor-id="conclusion-1">Conclusion</h2>
<p>The linear regression analysis conducted for the three research questions of this study provides valuable insights into the factors affecting student stress and mental health. For Research Question 1, we found a significant positive relationship between academic workload and stress levels, suggesting that students with heavier workloads tend to experience higher levels of stress.</p>
<p>In Research Question 2, while academic workload did not significantly impact the amount of sleep, missed social events were found to significantly reduce hours of sleep, which may contribute to poor mental health.</p>
<p>For Research Question 3, missed social events and living situations were marginally significant predictors of stress, indicating that students who miss social events or live on campus tend to report higher stress levels. These findings highlight the importance of considering multiple factors in understanding a student’s overall well-being.</p>
<p>However, the limitations of this analysis, including potential issues with sample randomization and measurement quality, should be addressed in future research to enhance the robustness and accuracy of the results. Future studies should also explore other possible variables, such as social support and coping mechanisms, which may further explain the mental health challenges faced by students.</p>
<p>We also conducted ANOVA testing for the three research questions for this study.</p>
<p>Research question 1 (RQ1), questions if academic workload contributes to a student’s stress levels. The results of the ANOVA test between the variables, stress and academic_workload also suggested that there is a significant relationship between a student’s academic workload and levels and stress.</p>
<p>Next, the ANOVA test for the second research question, if a student’s mental health is affected by their quality of sleep, suggested that there is not enough evidence to imply that there is a relationship between the variables hours_sleep and stress.</p>
<p>Finally, the ANOVA test for RQ3 gave us insight on whether a student’s mental health is affected by their ability to keep a work-life balance. The results of this analysis did not show evidence pointing towards a significant relationship between the variables, missed_social_events and stress.</p>
<p>Future and further research would greatly benefit from having a larger population size, since we could not go with the assumption that each group has a normal population distribution in each categorical group, since the CLT could not be satisfied due to the fact that each group did not have more than 30 observations.</p>
</section>
<section id="documentation-of-ai-tool-usage-1" class="level2">
<h2 class="anchored" data-anchor-id="documentation-of-ai-tool-usage-1">Documentation of AI Tool Usage</h2>
<p>We utilized generative AI tools, namely ChatGPT, to help refine our ideas and improve readability. These tools were used primarily for brainstorming, grammar corrections, and the explanations of certain sections. However, all the analytical work, including statistical methods and interpretation of results, was done by the authors.</p>
<p>https://chatgpt.com/share/674a3a7d-83e4-8013-a381-4192bb2028da</p>
<ol type="1">
<li>Beiter, R., Nash, R., McCrady, M., Rhoades, D., Linscomb, M., Clarahan, M., &amp; Sammut, S. (2015). The prevalence and correlates of depression, anxiety, and stress in a sample of college students. <em>Journal of Affective Disorders</em>, 173(3), 90-96.</li>
<li>Galambos, N. L., Howard, A. L., &amp; Krahn, H. J. (2009). Work, stress, and academic performance in university students. <em>Journal of Youth and Adolescence</em>, 38(4), 490-503.</li>
<li>Hershner, S. D., &amp; Chervin, R. D. (2014). Causes and consequences of sleepiness among college students. <em>Nature and Science of Sleep</em>, 6, 73-84.</li>
<li>Kim, E., &amp; Koh, K. (2018). Work-life balance and well-being among college students: A critical literature review. <em>Journal of College Counseling</em>, 21(3), 247-261.</li>
</ol>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>